// apps/frontend/src/components/PersonFormDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { usePersonStore } from '@/stores/person'
import type { PersonCreate, PersonUpdate } from '@person-timeline/api-types'
import { ElMessage, ElMessageBox } from 'element-plus'

const props = defineProps<{
  visible: boolean
  personId: string | null
}>()

const emit = defineEmits<{
  'update:visible': [value: boolean]
  saved: []
}>()

const store = usePersonStore()
const isCreate = computed(() => !props.personId)

const form = ref<PersonCreate>({
  name: '',
  birth_date: null,
  death_date: null,
  birth_display: null,
  death_display: null,
  summary: null,
})

const statusValue = ref<'draft' | 'published'>('draft')

// ========== 别名 ==========
const newAlias = ref('')
const aliasSubmitting = ref(false)

async function handleAddAlias() {
  if (!newAlias.value.trim() || !props.personId) return
  aliasSubmitting.value = true
  try {
    await store.addAlias(props.personId, newAlias.value.trim())
    newAlias.value = ''
    ElMessage.success('别名已添加')
  } finally {
    aliasSubmitting.value = false
  }
}

async function handleRemoveAlias(alias: string) {
  if (!props.personId) return
  try {
    await ElMessageBox.confirm(`确定删除别名「${alias}」？`, '确认', { type: 'warning' })
    await store.removeAlias(props.personId, alias)
    ElMessage.success('别名已删除')
  } catch {
    // cancelled
  }
}

// ========== 保存 ==========
async function handleSave() {
  if (!form.value.name?.trim()) {
    ElMessage.warning('请输入人物姓名')
    return
  }
  try {
    if (isCreate.value) {
      await store.create(form.value as PersonCreate)
      ElMessage.success('人物创建成功')
    } else if (props.personId) {
      const data: PersonUpdate = { ...form.value, status: statusValue.value }
      await store.update(props.personId, data)
      ElMessage.success('保存成功')
    }
    emit('saved')
    emit('update:visible', false)
  } catch {
    ElMessage.error('保存失败')
  }
}

// ========== 删除 ==========
async function handleDelete() {
  if (!props.personId) return
  try {
    await ElMessageBox.confirm(
      `确定删除人物「${form.value.name}」？此操作不可撤销。`,
      '确认删除',
      { type: 'warning', confirmButtonText: '删除', confirmButtonClass: 'el-button--danger' }
    )
    await store.remove(props.personId)
    ElMessage.success('人物已删除')
    emit('saved')
    emit('update:visible', false)
  } catch {
    // cancelled
  }
}

// ========== 监听弹框打开 ==========
watch(() => props.visible, async (val) => {
  if (!val) return

  store.resetCurrent()

  if (!isCreate.value && props.personId) {
    const person = await store.fetchById(props.personId)
    if (person) {
      form.value = {
        name: person.name,
        birth_date: person.birth_date,
        death_date: person.death_date,
        birth_display: person.birth_display,
        death_display: person.death_display,
        summary: person.summary,
      }
      statusValue.value = person.status
    }
  } else {
    form.value = {
      name: '',
      birth_date: null,
      death_date: null,
      birth_display: null,
      death_display: null,
      summary: null,
    }
    statusValue.value = 'draft'
  }
})
</script>

<template>
  <el-dialog
    :model-value="visible"
    @update:model-value="emit('update:visible', $event)"
    :title="isCreate ? '新建人物' : '编辑人物'"
    width="640px"
    :close-on-click-modal="false"
    destroy-on-close
  >
    <template v-if="!store.detailLoading">
      <!-- 基本信息 -->
      <el-form label-position="top" size="default">
        <div class="grid grid-cols-2 gap-4">
          <el-form-item label="姓名">
            <el-input v-model="form.name" placeholder="人物姓名" clearable />
          </el-form-item>
          <el-form-item label="状态" v-if="!isCreate">
            <el-select v-model="statusValue" class="!w-full">
              <el-option label="草稿" value="draft" />
              <el-option label="已发布" value="published" />
            </el-select>
          </el-form-item>
          <el-form-item label="出生日期">
            <el-date-picker
              v-model="form.birth_date"
              type="date"
              placeholder="选择出生日期"
              value-format="YYYY-MM-DD"
              class="!w-full"
              clearable
            />
          </el-form-item>
          <el-form-item label="死亡日期">
            <el-date-picker
              v-model="form.death_date"
              type="date"
              placeholder="选择死亡日期"
              value-format="YYYY-MM-DD"
              class="!w-full"
              clearable
            />
          </el-form-item>
          <el-form-item label="出生时间显示文本">
            <el-input v-model="form.birth_display" placeholder="如：约公元 181 年" clearable />
          </el-form-item>
          <el-form-item label="死亡时间显示文本">
            <el-input v-model="form.death_display" placeholder="如：公元 234 年 10 月" clearable />
          </el-form-item>
        </div>
        <el-form-item label="简介">
          <el-input v-model="form.summary" type="textarea" :rows="3" placeholder="人物简介..." />
        </el-form-item>
      </el-form>

      <!-- 别名管理 -->
      <template v-if="!isCreate">
        <el-divider />
        <h3 class="mb-3 text-base font-medium text-gray-900">别名</h3>
        <div class="mb-3 flex items-center gap-2">
          <el-input
            v-model="newAlias"
            placeholder="输入别名"
            clearable
            @keyup.enter="handleAddAlias"
          />
          <el-button
            type="primary"
            :disabled="!newAlias.trim()"
            :loading="aliasSubmitting"
            @click="handleAddAlias"
          >
            添加
          </el-button>
        </div>
        <div class="flex flex-wrap gap-2">
          <el-tag
            v-for="alias in store.aliases"
            :key="alias"
            closable
            :disable-transitions="true"
            @close="handleRemoveAlias(alias)"
          >
            {{ alias }}
          </el-tag>
          <span v-if="store.aliases.length === 0" class="text-sm text-gray-400">暂无别名</span>
        </div>
      </template>
    </template>

    <template v-else>
      <div class="flex items-center justify-center py-12">
        <el-icon class="is-loading" :size="24"><Loading /></el-icon>
        <span class="ml-2 text-gray-500">加载中...</span>
      </div>
    </template>

    <template #footer>
      <div class="flex items-center justify-between">
        <div>
          <el-button
            v-if="!isCreate"
            type="danger"
            plain
            @click="handleDelete"
          >
            删除
          </el-button>
        </div>
        <div class="flex items-center gap-2">
          <el-button @click="emit('update:visible', false)">取消</el-button>
          <el-button type="primary" :loading="store.saving" @click="handleSave">
            {{ store.saving ? '保存中...' : '保存' }}
          </el-button>
        </div>
      </div>
    </template>
  </el-dialog>
</template>

// apps/frontend/src/components/PersonFormDialog.tsx
import { useEffect, useState } from 'react'
import { Modal, Form, Input, Select, DatePicker, Button, Tag, Divider, message } from 'antd'
import { usePersonStore } from '@/stores/person'
import type { PersonCreate, PersonUpdate } from '@person-timeline/api-types'
import dayjs from 'dayjs'

interface PersonFormDialogProps {
  open: boolean
  personId: string | null
  onClose: () => void
  onSaved: () => void
}

export default function PersonFormDialog({ open, personId, onClose, onSaved }: PersonFormDialogProps) {
  const store = usePersonStore()
  const [form] = Form.useForm()
  const [aliasInput, setAliasInput] = useState('')
  const isCreate = personId === null

  useEffect(() => {
    if (open && personId) {
      store.fetchById(personId).then(person => {
        form.setFieldsValue({
          name: person.name,
          birth_date: person.birth_date ? dayjs(person.birth_date) : undefined,
          death_date: person.death_date ? dayjs(person.death_date) : undefined,
          birth_display: person.birth_display || '',
          death_display: person.death_display || '',
          summary: person.summary || '',
          status: person.status,
        })
      })
    } else if (open) {
      form.resetFields()
      store.resetCurrent()
    }
  }, [open, personId])

  const handleSave = async () => {
    try {
      const values = await form.validateFields()
      const payload: PersonCreate = {
        name: values.name,
        birth_date: values.birth_date?.format('YYYY-MM-DD') ?? null,
        death_date: values.death_date?.format('YYYY-MM-DD') ?? null,
        birth_display: values.birth_display || null,
        death_display: values.death_display || null,
        summary: values.summary || null,
      }

      if (isCreate) {
        await store.create(payload)
      } else {
        const updateData: PersonUpdate = {
          ...payload,
          status: values.status,
        }
        await store.update(personId, updateData)
      }
      message.success(isCreate ? '人物创建成功' : '人物更新成功')
      onSaved()
      onClose()
    } catch {
      // validation failed or API error
    }
  }

  const handleDelete = () => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除该人物吗？此操作不可恢复。',
      okText: '删除',
      okType: 'danger',
      cancelText: '取消',
      onOk: async () => {
        if (personId) {
          await store.remove(personId)
          message.success('人物已删除')
          onSaved()
          onClose()
        }
      },
    })
  }

  const handleAddAlias = async () => {
    if (!aliasInput.trim() || !personId) return
    try {
      await store.addAlias(personId, aliasInput.trim())
      setAliasInput('')
      message.success('别名添加成功')
    } catch {
      // error handled by interceptor
    }
  }

  const handleRemoveAlias = (alias: string) => {
    Modal.confirm({
      title: '确认删除',
      content: `确定要删除别名 "${alias}" 吗？`,
      okText: '删除',
      okType: 'danger',
      cancelText: '取消',
      onOk: async () => {
        if (personId) {
          await store.removeAlias(personId, alias)
          message.success('别名已删除')
        }
      },
    })
  }

  return (
    <Modal
      title={isCreate ? '新建人物' : '编辑人物'}
      open={open}
      onCancel={onClose}
      width={640}
      destroyOnClose
      footer={
        <div className="flex items-center justify-between">
          <div>
            {!isCreate && (
              <Button danger onClick={handleDelete}>
                删除
              </Button>
            )}
          </div>
          <div className="flex gap-2">
            <Button onClick={onClose}>取消</Button>
            <Button type="primary" loading={store.saving} onClick={handleSave}>
              {store.saving ? '保存中...' : '保存'}
            </Button>
          </div>
        </div>
      }
    >
      {store.detailLoading ? (
        <div className="flex items-center justify-center py-12 text-gray-400">加载中...</div>
      ) : (
        <Form form={form} layout="vertical">
          <div className="grid grid-cols-2 gap-4">
            <Form.Item name="name" label="姓名" rules={[{ required: true, message: '请输入姓名' }]}>
              <Input placeholder="请输入姓名" />
            </Form.Item>
            {!isCreate && (
              <Form.Item name="status" label="状态">
                <Select>
                  <Select.Option value="draft">草稿</Select.Option>
                  <Select.Option value="published">已发布</Select.Option>
                </Select>
              </Form.Item>
            )}
            <Form.Item name="birth_date" label="出生日期">
              <DatePicker format="YYYY-MM-DD" className="!w-full" placeholder="选择日期" />
            </Form.Item>
            <Form.Item name="death_date" label="死亡日期">
              <DatePicker format="YYYY-MM-DD" className="!w-full" placeholder="选择日期" />
            </Form.Item>
            <Form.Item name="birth_display" label="出生显示文本">
              <Input placeholder="如：建安十二年" />
            </Form.Item>
            <Form.Item name="death_display" label="死亡显示文本">
              <Input placeholder="如：建兴十二年" />
            </Form.Item>
          </div>
          <Form.Item name="summary" label="简介">
            <Input.TextArea rows={3} placeholder="输入人物简介" />
          </Form.Item>
        </Form>
      )}

      {!isCreate && (
        <>
          <Divider />
          <div className="space-y-3">
            <div className="text-sm font-medium text-gray-700">别名管理</div>
            <div className="flex gap-2">
              <Input
                value={aliasInput}
                onChange={e => setAliasInput(e.target.value)}
                placeholder="输入别名"
                className="flex-1"
                onPressEnter={handleAddAlias}
              />
              <Button onClick={handleAddAlias}>添加</Button>
            </div>
            <div className="flex flex-wrap gap-2">
              {store.aliases.length > 0 ? (
                store.aliases.map(alias => (
                  <Tag
                    key={alias}
                    closable
                    onClose={() => handleRemoveAlias(alias)}
                  >
                    {alias}
                  </Tag>
                ))
              ) : (
                <span className="text-sm text-gray-400">暂无别名</span>
              )}
            </div>
          </div>
        </>
      )}
    </Modal>
  )
}
