// apps/frontend2/src/components/Timeline.tsx
import { useRef, useEffect, useMemo, useCallback } from 'react'
import * as d3 from 'd3'
import { Tag } from 'antd'
import type { PersonEventItem } from '@person-timeline/api-types'

const MARGIN = { top: 40, right: 40, bottom: 80, left: 40 }
const INNER_H = 120

const EVENT_LABELS: Record<string, string> = {
  BIRTH: '出生',
  DEATH: '死亡',
  EDUCATION: '教育',
  CAREER: '仕途',
  CREATION: '创作',
  HISTORICAL: '历史',
  OTHER: '其他',
}

const TIME_LABELS: Record<string, string> = {
  POINT: '时间点',
  PERIOD: '时间段',
  FUZZY: '模糊',
}

interface TimelineProps {
  events: PersonEventItem[]
  height?: number
  timelineColor?: string
  onSelect?: (eventId: string) => void
}

export default function Timeline({ events, height = 500, timelineColor = '#3b82f6', onSelect }: TimelineProps) {
  const svgRef = useRef<SVGSVGElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const tooltipRef = useRef<HTMLDivElement>(null)
  const zoomTransform = useRef(d3.zoomIdentity)
  const resizeObserverRef = useRef<ResizeObserver | null>(null)

  const fuzzyEvents = useMemo(
    () => events.filter(e => e.time_type === 'FUZZY'),
    [events],
  )

  const render = useCallback(() => {
    const svgEl = svgRef.current
    const containerEl = containerRef.current
    if (!svgEl || !containerEl) return

    const svg = d3.select(svgEl)
    svg.selectAll('*').remove()

    const width = containerEl.clientWidth || 800
    const innerW = width - MARGIN.left - MARGIN.right

    const visibleEvents = events.filter(e => e.time_type !== 'FUZZY')
    if (visibleEvents.length === 0) return

    const dates = visibleEvents.flatMap(e => {
      const d: Date[] = []
      if (e.start_date) d.push(new Date(e.start_date))
      if (e.end_date) d.push(new Date(e.end_date))
      return d
    })
    const minDate = d3.min(dates)!
    const maxDate = d3.max(dates)!
    const pad = (maxDate.getTime() - minDate.getTime()) * 0.05 || 86400000
    const xScale = d3.scaleTime()
      .domain([new Date(minDate.getTime() - pad), new Date(maxDate.getTime() + pad)])
      .range([0, innerW])
    const midY = INNER_H / 2

    const g = svg.append('g')
      .attr('transform', `translate(${MARGIN.left},${MARGIN.top})`)

    // zoom
    const zoom = d3.zoom<SVGSVGElement, unknown>()
      .scaleExtent([1, 20])
      .translateExtent([[0, 0], [innerW, INNER_H]])
      .on('zoom', (event) => {
        zoomTransform.current = event.transform
        render()
      })

    svg.call(zoom)
    svg.call(zoom.transform, zoomTransform.current)

    const rescaledX = zoomTransform.current.rescaleX(xScale)

    // main axis
    g.append('line')
      .attr('x1', 0).attr('y1', midY)
      .attr('x2', innerW).attr('y2', midY)
      .attr('stroke', '#d1d5db').attr('stroke-width', 2)

    // sub-timeline for PERIOD hover
    const subGroup = g.append('g').attr('class', 'sub-timeline').style('display', 'none')
    subGroup.append('rect').attr('class', 'sub-rect')
    subGroup.append('text').attr('class', 'sub-start-label').attr('y', 90).attr('font-size', 11).attr('fill', '#6b7280')
    subGroup.append('text').attr('class', 'sub-end-label').attr('y', 105).attr('font-size', 11).attr('fill', '#6b7280')
    subGroup.append('line').attr('class', 'sub-line')

    // x-axis
    const axisG = g.append('g')
      .attr('transform', `translate(0,${INNER_H})`)

    const yearTicks = rescaledX.ticks(d3.timeYear.every(1)!)
    axisG.selectAll('line')
      .data(yearTicks).join('line')
      .attr('x1', d => rescaledX(d)).attr('x2', d => rescaledX(d))
      .attr('y1', 0).attr('y2', 5)
      .attr('stroke', '#9ca3af')

    axisG.selectAll('text')
      .data(yearTicks).join('text')
      .attr('x', d => rescaledX(d))
      .attr('y', 20)
      .attr('text-anchor', 'middle')
      .attr('font-size', 11)
      .attr('fill', d => {
        const y = rescaledX(d)
        return (y <= 0 || y >= innerW) ? 'transparent' : '#6b7280'
      })
      .attr('font-weight', d => {
        const y = rescaledX(d)
        return (y <= 0 || y >= innerW) ? 'normal' : 'bold'
      })
      .text(d => d3.timeFormat('%Y')(d))

    // grid lines
    axisG.selectAll('.grid-line')
      .data(yearTicks).join('line')
      .attr('class', 'grid-line')
      .attr('x1', d => rescaledX(d)).attr('x2', d => rescaledX(d))
      .attr('y1', -midY).attr('y2', 0)
      .attr('stroke', '#e5e7eb')
      .attr('stroke-dasharray', d => {
        const y = rescaledX(d)
        return (y <= 0 || y >= innerW) ? '0' : '4,4'
      })

    // event markers
    visibleEvents.forEach(ev => {
      const x = ev.start_date ? rescaledX(new Date(ev.start_date)) : 0
      let marker: d3.Selection<SVGElement, unknown, null, undefined>

      if (ev.event_type === 'BIRTH') {
        marker = g.append('text')
          .attr('x', x).attr('y', midY + 8)
          .attr('text-anchor', 'middle')
          .attr('font-size', 22).attr('fill', '#eab308')
          .text('★') as any
      } else if (ev.event_type === 'DEATH') {
        const s = 6
        marker = g.append('path')
          .attr('d', d3.symbol().type(d3.symbolDiamond).size(s * s * 3)())
          .attr('transform', `translate(${x},${midY})`)
          .attr('fill', '#ef4444') as any
      } else if (ev.time_type === 'PERIOD') {
        marker = g.append('rect')
          .attr('x', x - 8).attr('y', midY - 8)
          .attr('width', 16).attr('height', 16)
          .attr('rx', 3).attr('ry', 3)
          .attr('fill', timelineColor) as any
      } else {
        marker = g.append('circle')
          .attr('cx', x).attr('cy', midY)
          .attr('r', 7).attr('fill', timelineColor) as any
      }

      marker
        .style('cursor', 'pointer')
        .on('mouseenter', (event: MouseEvent) => {
          const tooltip = d3.select(tooltipRef.current)
          tooltip.style('display', 'block')
            .html(`
              <div class="font-medium">${ev.personal_title || ev.title}</div>
              <div class="text-xs text-gray-500 mt-1">${ev.start_date || ''}${ev.end_date ? ` — ${ev.end_date}` : ''}</div>
              <div class="text-xs text-gray-400 mt-1">${EVENT_LABELS[ev.event_type] || ev.event_type} · ${TIME_LABELS[ev.time_type] || ev.time_type}</div>
            `)

          const containerRect = containerEl.getBoundingClientRect()
          let tx = event.clientX - containerRect.left + 12
          let ty = event.clientY - containerRect.top - 10
          if (tx + 200 > width) tx = event.clientX - containerRect.left - 200 - 12
          if (ty < 0) ty = 10
          tooltip.style('left', `${tx}px`).style('top', `${ty}px`)

          // PERIOD sub-timeline
          if (ev.time_type === 'PERIOD') {
            const subX = ev.end_date ? rescaledX(new Date(ev.end_date)) : x
            subGroup.style('display', 'block')
            subGroup.select('.sub-line')
              .attr('x1', x).attr('y1', midY + 16)
              .attr('x2', subX).attr('y2', midY + 22)
              .attr('stroke', '#9ca3af').attr('stroke-width', 2)
            subGroup.select('.sub-rect')
              .attr('x', Math.min(x, subX) - 40)
              .attr('y', midY + 24)
              .attr('width', Math.abs(subX - x) + 80)
              .attr('height', 40)
              .attr('rx', 6)
              .attr('fill', '#f3f4f6').attr('stroke', '#d1d5db')
            subGroup.select('.sub-start-label')
              .attr('x', x).attr('text-anchor', 'middle')
              .text(ev.start_date ? d3.timeFormat('%Y/%m/%d')(new Date(ev.start_date)) : '')
            subGroup.select('.sub-end-label')
              .attr('x', subX).attr('text-anchor', 'middle')
              .text(ev.end_date ? d3.timeFormat('%Y/%m/%d')(new Date(ev.end_date)) : '')
          }
        })
        .on('mousemove', (event: MouseEvent) => {
          const tooltip = d3.select(tooltipRef.current)
          const containerRect = containerEl.getBoundingClientRect()
          let tx = event.clientX - containerRect.left + 12
          let ty = event.clientY - containerRect.top - 10
          if (tx + 200 > width) tx = event.clientX - containerRect.left - 200 - 12
          if (ty < 0) ty = 10
          tooltip.style('left', `${tx}px`).style('top', `${ty}px`)
        })
        .on('mouseleave', () => {
          d3.select(tooltipRef.current).style('display', 'none')
          subGroup.style('display', 'none')
        })
        .on('click', () => {
          onSelect?.(ev.event_id)
        })
    })
  }, [events, timelineColor, onSelect])

  useEffect(() => {
    render()
  }, [render])

  useEffect(() => {
    zoomTransform.current = d3.zoomIdentity
    render()
  }, [events])

  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    const ro = new ResizeObserver(() => render())
    ro.observe(el)
    resizeObserverRef.current = ro
    return () => ro.disconnect()
  }, [])

  return (
    <div className="flex gap-6">
      <div ref={containerRef} className="flex-1 min-w-0 relative">
        <svg ref={svgRef} width="100%" height={height} />
        <div
          ref={tooltipRef}
          className="hidden absolute z-10 rounded-lg border bg-white px-3 py-2 shadow-lg pointer-events-none text-sm"
        />
        {events.filter(e => e.time_type !== 'FUZZY').length === 0 && (
          <div className="text-center text-gray-400 py-8">暂无事件数据</div>
        )}
      </div>

      {fuzzyEvents.length > 0 && (
        <div className="w-64 shrink-0">
          <div className="text-sm font-medium text-gray-500 mb-2">模糊事件 ({fuzzyEvents.length})</div>
          <div className="space-y-2">
            {fuzzyEvents.map(ev => (
              <div
                key={ev.event_id}
                className="rounded-lg border bg-white p-3 cursor-pointer hover:shadow-sm transition-shadow"
                onClick={() => onSelect?.(ev.event_id)}
              >
                <div className="text-sm font-medium">{ev.personal_title || ev.title}</div>
                <div className="text-xs text-gray-500 mt-1">
                  {ev.start_date}{ev.end_date ? ` — ${ev.end_date}` : ''}
                </div>
                <Tag className="!mt-1" style={{ color: timelineColor, borderColor: timelineColor }}>
                  {EVENT_LABELS[ev.event_type] || ev.event_type}
                </Tag>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// apps/frontend/src/components/Timeline.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch, onUnmounted } from 'vue'
import * as d3 from 'd3'
import type { PersonEventItem, EventType, TimeType } from '@person-timeline/api-types'

const props = withDefaults(defineProps<{
  events: PersonEventItem[]
  height?: number
  timelineColor?: string
}>(), {
  height: 500,
  timelineColor: '#3b82f6',
})

const emit = defineEmits<{
  select: [eventId: string]
}>()

const svgRef = ref<SVGSVGElement | null>(null)
const svgContainerRef = ref<HTMLDivElement | null>(null)
const tooltipRef = ref<HTMLDivElement | null>(null)

// ========== 常量 ==========
const MARGIN = { top: 40, right: 40, bottom: 80, left: 40 }
const EVENT_LABELS: Record<EventType, string> = {
  BIRTH: '出生',
  DEATH: '死亡',
  EDUCATION: '教育',
  CAREER: '仕途',
  CREATION: '创作',
  HISTORICAL: '历史',
  OTHER: '其他',
}
const TIME_LABELS: Record<TimeType, string> = {
  POINT: '时间点',
  PERIOD: '时间段',
  FUZZY: '模糊',
}

// FUZZY 事件单独提取到右侧卡片
const fuzzyEvents = computed(() => props.events.filter((e) => e.time_type === 'FUZZY'))

// ========== 缩放状态 ==========
let zoomTransform = d3.zoomIdentity

// ========== 渲染 ==========
function render() {
  const svg = d3.select(svgRef.value!)
  const container = svgContainerRef.value
  if (!container || props.events.length === 0) return

  svg.selectAll('*').remove()
  const width = container.clientWidth

  const visibleEvents = props.events.filter((e) => e.time_type !== 'FUZZY')
  if (visibleEvents.length === 0) return

  const innerH = 120
  const svgH = innerH + MARGIN.top + MARGIN.bottom
  svg.attr('height', Math.max(svgH, props.height))

  const innerW = width - MARGIN.left - MARGIN.right
  if (innerW <= 0) return

  const midY = innerH / 2

  // 时间范围
  const dates = visibleEvents.flatMap((e) => [new Date(e.start_date), new Date(e.end_date)])
  const minDate = d3.min(dates)!
  const maxDate = d3.max(dates)!
  const pad = (maxDate.getTime() - minDate.getTime()) * 0.05 || 86400000 * 365

  // 基础时间比例尺
  const baseScale = d3.scaleTime()
    .domain([new Date(minDate.getTime() - pad), new Date(maxDate.getTime() + pad)])
    .range([0, innerW])

  // 应用缩放变换
  const xScale = zoomTransform.rescaleX(baseScale)

  const g = svg.append('g').attr('transform', `translate(${MARGIN.left},${MARGIN.top})`)

  // ---- 时间轴线 ----
  g.append('line')
    .attr('x1', 0)
    .attr('x2', innerW)
    .attr('y1', midY)
    .attr('y2', midY)
    .attr('stroke', props.timelineColor)
    .attr('stroke-width', 2)

  // ---- PERIOD 子时间轴区域（默认隐藏） ----
  const subAxisY = innerH + 25
  const subTimelineG = g.append('g')
    .attr('class', 'sub-timeline')
    .style('display', 'none')

  subTimelineG.append('line')
    .attr('x1', 0)
    .attr('x2', innerW)
    .attr('y1', subAxisY)
    .attr('y2', subAxisY)
    .attr('stroke', '#e5e7eb')
    .attr('stroke-width', 1)

  subTimelineG.append('rect')
    .attr('y', subAxisY - 6)
    .attr('height', 12)
    .attr('fill', props.timelineColor)
    .attr('rx', 3)
    .attr('opacity', 0.8)

  subTimelineG.append('text')
    .attr('class', 'sub-label-start')
    .attr('y', subAxisY - 10)
    .attr('font-size', '11')
    .attr('fill', props.timelineColor)

  subTimelineG.append('text')
    .attr('class', 'sub-label-end')
    .attr('y', subAxisY - 10)
    .attr('font-size', '11')
    .attr('fill', props.timelineColor)
    .attr('text-anchor', 'end')

  // ---- X 轴（年份，去掉前置零） ----
  const xAxisGroup = g.append('g')
    .attr('transform', `translate(0,${innerH})`)
    .attr('class', 'timeline-x-axis')
    .call(d3.axisBottom(xScale)
      .tickFormat((d: Date | d3.NumberValue, _i: number) => `${(d as Date).getFullYear()}`)
      .tickSizeOuter(0)
      .tickSizeInner(6)
    )

  // 美化 X 轴样式
  xAxisGroup.selectAll('.domain')
    .attr('stroke', '#d1d5db')
    .attr('stroke-width', 1)
  xAxisGroup.selectAll('.tick line')
    .attr('stroke', '#d1d5db')
    .attr('stroke-width', 1)
  xAxisGroup.selectAll('.tick text')
    .attr('fill', '#6b7280')
    .attr('font-size', '11')
    .attr('font-weight', '500')
    .attr('dy', '0.3em')

  // 垂直网格虚线（从刻线延伸到时间轴上方）
  xAxisGroup.selectAll('.tick line')
    .attr('y2', -innerH)
    .attr('stroke', '#f3f4f6')
    .attr('stroke-width', 1)
    .attr('stroke-dasharray', '3,3')
  xAxisGroup.selectAll('.tick:first-child line, .tick:last-child line')
    .attr('stroke-dasharray', '0')

  // ---- 绘制事件 ----
  const eventGroup = g.append('g')
  const clipPathId = `timeline-clip-${Date.now()}`
  g.append('defs').append('clipPath')
    .attr('id', clipPathId)
    .append('rect')
    .attr('x', -5)
    .attr('width', innerW + 10)
    .attr('y', 0)
    .attr('height', innerH)

  visibleEvents.forEach((ev) => {
    const y = midY
    const x1 = xScale(new Date(ev.start_date))
    const x2 = xScale(new Date(ev.end_date))

    if (ev.event_type === 'BIRTH') {
      const group = eventGroup.append('g')
        .attr('cursor', 'pointer')
        .attr('data-event-id', ev.event_id)
        .attr('transform', `translate(${x1},${y})`)
        .attr('clip-path', `url(#${clipPathId})`)
      group.append('text')
        .attr('text-anchor', 'middle')
        .attr('dominant-baseline', 'central')
        .attr('font-size', '22')
        .attr('fill', '#eab308')
        .text('★')
      group
        .on('mouseenter', (e: MouseEvent) => showTooltip(e, ev))
        .on('mousemove', (e: MouseEvent) => moveTooltip(e))
        .on('mouseleave', hideTooltip)
        .on('click', () => emit('select', ev.event_id))
    } else if (ev.event_type === 'DEATH') {
      const group = eventGroup.append('g')
        .attr('cursor', 'pointer')
        .attr('data-event-id', ev.event_id)
        .attr('transform', `translate(${x1},${y})`)
        .attr('clip-path', `url(#${clipPathId})`)
      group.append('path')
        .attr('d', 'M0,-12 L12,0 L0,12 L-12,0 Z')
        .attr('fill', props.timelineColor)
        .attr('stroke', '#fff')
        .attr('stroke-width', 2)
      group
        .on('mouseenter', (e: MouseEvent) => showTooltip(e, ev))
        .on('mousemove', (e: MouseEvent) => moveTooltip(e))
        .on('mouseleave', hideTooltip)
        .on('click', () => emit('select', ev.event_id))
    } else if (ev.time_type === 'PERIOD') {
      // 时间段：16×16 方形
      eventGroup.append('rect')
        .attr('x', x1 - 8)
        .attr('y', y - 8)
        .attr('width', 16)
        .attr('height', 16)
        .attr('fill', props.timelineColor)
        .attr('rx', 2)
        .attr('cursor', 'pointer')
        .attr('data-event-id', ev.event_id)
        .attr('clip-path', `url(#${clipPathId})`)
        .on('mouseenter', (e: MouseEvent) => {
          showSubTimeline(ev, x1, x2)
          showTooltip(e, ev)
        })
        .on('mousemove', (e: MouseEvent) => moveTooltip(e))
        .on('mouseleave', () => {
          hideSubTimeline()
          hideTooltip()
        })
        .on('click', () => emit('select', ev.event_id))
    } else {
      // 时间点：实心圆
      eventGroup.append('circle')
        .attr('cx', x1)
        .attr('cy', y)
        .attr('r', 7)
        .attr('fill', props.timelineColor)
        .attr('stroke', '#fff')
        .attr('stroke-width', 2)
        .attr('cursor', 'pointer')
        .attr('data-event-id', ev.event_id)
        .attr('clip-path', `url(#${clipPathId})`)
        .on('mouseenter', (e: MouseEvent) => showTooltip(e, ev))
        .on('mousemove', (e: MouseEvent) => moveTooltip(e))
        .on('mouseleave', hideTooltip)
        .on('click', () => emit('select', ev.event_id))
    }
  })

  // ---- 缩放 + 拖拽 ----
  const zoom = d3.zoom<SVGSVGElement, unknown>()
    .scaleExtent([1, 20])
    .extent([[0, 0], [innerW, innerH]])
    .translateExtent([[0, 0], [innerW, innerH]])
    .on('zoom', (event: d3.D3ZoomEvent<SVGSVGElement, unknown>) => {
      if (!event.sourceEvent) return
      zoomTransform = event.transform
      render()
    })

  svg.call(zoom)

  // 恢复缩放状态（不触发 zoom 事件）
  if (zoomTransform !== d3.zoomIdentity) {
    svg.call(zoom.transform, zoomTransform)
  }
}

// ========== PERIOD 子时间轴 ==========
function showSubTimeline(ev: PersonEventItem, x1: number, x2: number) {
  const g = d3.select(svgRef.value!).select('.sub-timeline')
  if (g.empty()) return

  g.style('display', null)

  g.select('rect')
    .attr('x', x1)
    .attr('width', Math.max(x2 - x1, 8))

  const fmt = d3.timeFormat('%Y')
  g.select<SVGTextElement>('.sub-label-start')
    .text('')
    .append('tspan')
    .attr('x', x1)
    .text(`${fmt(new Date(ev.start_date))}`)
    .append('tspan')
    .attr('x', x1)
    .attr('dy', '1.2em')
    .attr('font-size', '10')
    .attr('fill', '#9ca3af')
    .text(ev.start_date.slice(5, 10))

  g.select<SVGTextElement>('.sub-label-end')
    .text('')
    .append('tspan')
    .attr('x', x2)
    .text(`${fmt(new Date(ev.end_date))}`)
    .append('tspan')
    .attr('x', x2)
    .attr('dy', '1.2em')
    .attr('font-size', '10')
    .attr('fill', '#9ca3af')
    .text(ev.end_date.slice(5, 10))
}

function hideSubTimeline() {
  d3.select(svgRef.value!).select('.sub-timeline').style('display', 'none')
}

// ========== 工具提示 ==========
let tooltipVisible = false

function showTooltip(e: MouseEvent, ev: PersonEventItem) {
  const el = tooltipRef.value
  if (!el) return
  tooltipVisible = true
  el.classList.remove('hidden')
  el.innerHTML = `
    <div class="font-medium text-gray-900 text-sm">${ev.personal_title || ev.title}</div>
    <div class="text-xs text-gray-500 mt-0.5">
      ${ev.start_date.slice(0, 10)} ~ ${ev.end_date.slice(0, 10)}
      <span class="ml-2">${EVENT_LABELS[ev.event_type]}</span>
    </div>
    <div class="text-xs text-gray-400 mt-0.5">${TIME_LABELS[ev.time_type]}</div>
  `
  moveTooltip(e)
}

function moveTooltip(e: MouseEvent) {
  if (!tooltipVisible || !tooltipRef.value) return
  const rect = svgContainerRef.value!.getBoundingClientRect()
  let left = e.clientX - rect.left + 12
  let top = e.clientY - rect.top - 8
  const tw = tooltipRef.value.offsetWidth
  const th = tooltipRef.value.offsetHeight
  if (left + tw > rect.width - 10) left = e.clientX - rect.left - tw - 12
  if (top + th > rect.height - 10) top = rect.height - th - 10
  if (top < 10) top = 10
  tooltipRef.value.style.left = `${left}px`
  tooltipRef.value.style.top = `${top}px`
}

function hideTooltip() {
  tooltipVisible = false
  const el = tooltipRef.value
  if (el) el.classList.add('hidden')
}

// ========== 生命周期 ==========
const resizeObserver = ref<ResizeObserver | null>(null)

onMounted(() => {
  render()
  if (svgContainerRef.value) {
    resizeObserver.value = new ResizeObserver(() => render())
    resizeObserver.value.observe(svgContainerRef.value)
  }
})

onUnmounted(() => {
  resizeObserver.value?.disconnect()
})

watch(() => props.events, () => {
  zoomTransform = d3.zoomIdentity
  render()
}, { deep: false })
</script>

<template>
  <div class="relative w-full flex gap-6">
    <!-- 左侧：SVG 时间轴 -->
    <div ref="svgContainerRef" class="flex-1 min-w-0">
      <svg ref="svgRef" class="w-full" :height="height"></svg>
      <div
        ref="tooltipRef"
        class="hidden absolute pointer-events-none z-10 rounded-lg border border-gray-200 bg-white px-3 py-2 shadow-lg"
      ></div>
      <div v-if="events.length === 0" class="flex items-center justify-center py-20 text-sm text-gray-400">
        暂无事件数据
      </div>
    </div>

    <!-- 右侧：模糊事件卡片 -->
    <div v-if="fuzzyEvents.length > 0" class="w-64 shrink-0">
      <h3 class="mb-3 text-sm font-semibold text-gray-700 border-b border-gray-200 pb-2">
        模糊事件
        <span class="ml-1 font-normal text-gray-400">({{ fuzzyEvents.length }})</span>
      </h3>
      <div class="space-y-3">
        <div
          v-for="ev in fuzzyEvents"
          :key="ev.event_id"
          class="cursor-pointer rounded-lg border border-gray-200 bg-white p-3 transition-colors hover:border-primary-300 hover:bg-primary-50"
          @click="emit('select', ev.event_id)"
        >
          <div class="text-sm font-medium text-gray-900">{{ ev.personal_title || ev.title }}</div>
          <div class="mt-1 text-xs text-gray-500">
            {{ ev.start_date.slice(0, 10) }} ~ {{ ev.end_date.slice(0, 10) }}
          </div>
          <div class="mt-1">
            <el-tag size="small" :color="props.timelineColor" class="!text-white !border-0">
              {{ EVENT_LABELS[ev.event_type] }}
            </el-tag>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
