// apps/frontend/src/views/admin/EventList.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useEventStore } from '@/stores/event'
import { ElMessage, ElMessageBox } from 'element-plus'
import EventFormDialog from '@/components/EventFormDialog.vue'

const route = useRoute()
const router = useRouter()
const store = useEventStore()

// ========== 筛选 ==========
const search = ref('')
const eventTypeFilter = ref('')
const timeTypeFilter = ref('')
const personIdFilter = ref<string | undefined>(undefined)
const personNameFilter = ref<string | undefined>(undefined)
let debounceTimer: ReturnType<typeof setTimeout> | null = null

const EVENT_TYPE_LABELS: Record<string, string> = {
  BIRTH: '出生',
  DEATH: '死亡',
  EDUCATION: '教育',
  CAREER: '仕途',
  CREATION: '创作',
  HISTORICAL: '历史',
  OTHER: '其他',
}

const EVENT_TYPE_TYPES: Record<string, 'success' | 'danger' | 'primary' | 'warning' | 'info'> = {
  BIRTH: 'success',
  DEATH: 'danger',
  EDUCATION: 'primary',
  CAREER: 'warning',
  CREATION: 'primary',
  HISTORICAL: 'info',
  OTHER: 'info',
}

const TIME_TYPE_LABELS: Record<string, string> = {
  POINT: '时间点',
  PERIOD: '时间段',
  FUZZY: '模糊',
}

watch([search, eventTypeFilter, timeTypeFilter], () => {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    currentPage.value = 1
    fetchData()
  }, 300)
})

// ========== 分页 ==========
const currentPage = ref(1)

function fetchData() {
  store.fetchList({
    page: currentPage.value,
    search: search.value || undefined,
    event_type: (eventTypeFilter.value || undefined) as import('@person-timeline/api-types').EventType | undefined,
    time_type: (timeTypeFilter.value || undefined) as import('@person-timeline/api-types').TimeType | undefined,
    person_id: personIdFilter.value,
  })
}

function onPageChange(p: number) {
  currentPage.value = p
  fetchData()
}

// ========== 人物筛选 ==========
function clearPersonFilter() {
  personIdFilter.value = undefined
  personNameFilter.value = undefined
  currentPage.value = 1
  fetchData()
  router.replace({ query: {} })
}

// ========== 弹出框 ==========
const dialogVisible = ref(false)
const editingEventId = ref<string | null>(null)

function openCreate() {
  editingEventId.value = null
  dialogVisible.value = true
}

function openEdit(id: string) {
  editingEventId.value = id
  dialogVisible.value = true
}

function onDialogSaved() {
  fetchData()
}

// ========== 删除 ==========
async function handleDelete(id: string, title: string) {
  try {
    await ElMessageBox.confirm(
      `确定删除事件「${title}」？此操作不可撤销。`,
      '确认删除',
      { type: 'warning', confirmButtonText: '删除' }
    )
    await store.remove(id)
    ElMessage.success('事件已删除')
    fetchData()
  } catch {
    // cancelled
  }
}

// ========== 初始化 ==========
onMounted(() => {
  const pid = route.query.person_id as string | undefined
  const pname = route.query.person_name as string | undefined
  if (pid) {
    personIdFilter.value = pid
    personNameFilter.value = pname
  }
  fetchData()
})
</script>

<template>
  <div>
    <!-- 头部 -->
    <div class="mb-6 flex items-center justify-between">
      <h2 class="text-xl font-semibold text-gray-900">事件管理</h2>
      <el-button type="primary" @click="openCreate">+ 新建事件</el-button>
    </div>

    <!-- 筛选 -->
    <div class="mb-4 flex items-center gap-4">
      <el-input
        v-model="search"
        placeholder="搜索事件标题..."
        clearable
        style="width: 280px"
      />
      <el-select v-model="eventTypeFilter" placeholder="全部类型" clearable style="width: 140px">
        <el-option label="全部类型" value="" />
        <el-option v-for="(label, key) in EVENT_TYPE_LABELS" :key="key" :label="label" :value="key" />
      </el-select>
      <el-select v-model="timeTypeFilter" placeholder="全部时间类型" clearable style="width: 150px">
        <el-option label="全部时间类型" value="" />
        <el-option v-for="(label, key) in TIME_TYPE_LABELS" :key="key" :label="label" :value="key" />
      </el-select>
      <el-tag
        v-if="personNameFilter"
        closable
        type="primary"
        @close="clearPersonFilter"
      >
        筛选：{{ personNameFilter }}
      </el-tag>
    </div>

    <!-- 表格 -->
    <el-table
      :data="store.list"
      v-loading="store.listLoading"
      stripe
      style="width: 100%"
      empty-text="暂无事件数据"
    >
      <el-table-column prop="title" label="事件标题" min-width="160">
        <template #default="{ row }">
          <span class="font-medium text-gray-900">{{ row.title }}</span>
        </template>
      </el-table-column>
      <el-table-column label="类型" width="90">
        <template #default="{ row }">
          <el-tag :type="EVENT_TYPE_TYPES[row.event_type]" size="small">
            {{ EVENT_TYPE_LABELS[row.event_type] }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="时间" width="100">
        <template #default="{ row }">
          <el-tag size="small" effect="plain">
            {{ TIME_TYPE_LABELS[row.time_type] }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="关联人物" min-width="140">
        <template #default="{ row }">
          <span v-for="p in row.persons" :key="p.id" class="mr-1 inline-block text-gray-500">{{ p.name }}</span>
          <span v-if="row.persons.length === 0" class="text-gray-300">-</span>
        </template>
      </el-table-column>
      <el-table-column label="排序日期" width="110">
        <template #default="{ row }">
          <span class="text-gray-500">{{ row.sort_date?.slice(0, 10) }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="140" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" size="small" @click="openEdit(row.id)">编辑</el-button>
          <el-button link type="danger" size="small" @click="handleDelete(row.id, row.title)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <div v-if="store.total > store.pageSize" class="mt-4 flex justify-end">
      <el-pagination
        v-model:current-page="currentPage"
        :page-size="store.pageSize"
        :total="store.total"
        layout="total, prev, pager, next"
        background
        @current-change="onPageChange"
      />
    </div>

    <!-- 新建/编辑弹出框 -->
    <EventFormDialog
      v-model:visible="dialogVisible"
      :event-id="editingEventId"
      @saved="onDialogSaved"
    />
  </div>
</template>

// apps/frontend2/src/views/admin/EventList.tsx
import { useEffect, useState, useCallback } from 'react'
import { Button, Input, Select, Table, Tag, Pagination, message, Modal } from 'antd'
import { useEventStore } from '@/stores/event'
import EventFormDialog from '@/components/EventFormDialog'
import { useSearchParams } from 'react-router-dom'

const EVENT_TYPE_LABELS: Record<string, string> = {
  BIRTH: '出生',
  DEATH: '死亡',
  EDUCATION: '教育',
  CAREER: '仕途',
  CREATION: '创作',
  HISTORICAL: '历史',
  OTHER: '其他',
}

const EVENT_TYPE_COLORS: Record<string, string> = {
  BIRTH: 'success',
  DEATH: 'danger',
  EDUCATION: 'processing',
  CAREER: 'warning',
  CREATION: 'purple',
  HISTORICAL: 'geekblue',
  OTHER: 'default',
}

const TIME_TYPE_LABELS: Record<string, string> = {
  POINT: '时间点',
  PERIOD: '时间段',
  FUZZY: '模糊',
}

export default function EventList() {
  const store = useEventStore()
  const [searchParams, setSearchParams] = useSearchParams()
  const [search, setSearch] = useState('')
  const [eventTypeFilter, setEventTypeFilter] = useState('')
  const [timeTypeFilter, setTimeTypeFilter] = useState('')
  const [personIdFilter, setPersonIdFilter] = useState<string | undefined>(undefined)
  const [personNameFilter, setPersonNameFilter] = useState<string | undefined>(undefined)
  const [currentPage, setCurrentPage] = useState(1)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingEventId, setEditingEventId] = useState<string | null>(null)

  useEffect(() => {
    const pid = searchParams.get('person_id')
    const pname = searchParams.get('person_name')
    if (pid) setPersonIdFilter(pid)
    if (pname) setPersonNameFilter(pname)
  }, [])

  const fetchData = useCallback(() => {
    store.fetchList({
      page: currentPage,
      page_size: store.pageSize,
      search: search || undefined,
      event_type: (eventTypeFilter || undefined) as any,
      time_type: (timeTypeFilter || undefined) as any,
      person_id: personIdFilter,
    })
  }, [currentPage, search, eventTypeFilter, timeTypeFilter, personIdFilter])

  useEffect(() => {
    const timer = setTimeout(() => {
      setCurrentPage(1)
      fetchData()
    }, 300)
    return () => clearTimeout(timer)
  }, [search, eventTypeFilter, timeTypeFilter])

  useEffect(() => {
    fetchData()
  }, [currentPage, personIdFilter])

  const clearPersonFilter = () => {
    setPersonIdFilter(undefined)
    setPersonNameFilter(undefined)
    setCurrentPage(1)
    setSearchParams({})
  }

  const handleDelete = (id: string, title: string) => {
    Modal.confirm({
      title: '确认删除',
      content: `确定要删除事件「${title}」吗？此操作不可恢复。`,
      okText: '删除',
      okType: 'danger',
      cancelText: '取消',
      onOk: async () => {
        await store.remove(id)
        message.success('事件已删除')
        fetchData()
      },
    })
  }

  const columns = [
    {
      title: '事件标题',
      dataIndex: 'title',
      key: 'title',
      width: 160,
      render: (title: string) => <span className="font-medium">{title}</span>,
    },
    {
      title: '类型',
      dataIndex: 'event_type',
      key: 'event_type',
      width: 90,
      render: (type: string) => (
        <Tag color={EVENT_TYPE_COLORS[type] || 'default'}>{EVENT_TYPE_LABELS[type] || type}</Tag>
      ),
    },
    {
      title: '时间',
      dataIndex: 'time_type',
      key: 'time_type',
      width: 100,
      render: (type: string) => (
        <Tag>{TIME_TYPE_LABELS[type] || type}</Tag>
      ),
    },
    {
      title: '关联人物',
      key: 'persons',
      width: 140,
      render: (_: unknown, row: { persons?: { id: string; name: string }[] }) =>
        row.persons && row.persons.length > 0
          ? row.persons.map(p => p.name).join('、')
          : '-',
    },
    {
      title: '排序日期',
      key: 'sort_date',
      width: 110,
      render: (_: unknown, row: { sort_date?: string | null }) => row.sort_date?.slice(0, 10),
    },
    {
      title: '操作',
      key: 'actions',
      width: 140,
      fixed: 'right' as const,
      render: (_: unknown, row: { id: string; title: string }) => (
        <div className="flex gap-1">
          <Button type="link" size="small" onClick={() => { setEditingEventId(row.id); setDialogOpen(true) }}>
            编辑
          </Button>
          <Button type="link" size="small" danger onClick={() => handleDelete(row.id, row.title)}>
            删除
          </Button>
        </div>
      ),
    },
  ]

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold">事件管理</h2>
        <Button type="primary" onClick={() => { setEditingEventId(null); setDialogOpen(true) }}>
          + 新建事件
        </Button>
      </div>

      <div className="flex items-center gap-4 mb-4">
        <Input
          placeholder="搜索事件标题..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          allowClear
          style={{ width: 280 }}
        />
        <Select
          placeholder="全部类型"
          value={eventTypeFilter || undefined}
          onChange={v => setEventTypeFilter(v || '')}
          allowClear
          style={{ width: 140 }}
          onClear={() => setEventTypeFilter('')}
        >
          <Select.Option value="">全部类型</Select.Option>
          {Object.entries(EVENT_TYPE_LABELS).map(([key, label]) => (
            <Select.Option key={key} value={key}>{label}</Select.Option>
          ))}
        </Select>
        <Select
          placeholder="全部时间类型"
          value={timeTypeFilter || undefined}
          onChange={v => setTimeTypeFilter(v || '')}
          allowClear
          style={{ width: 150 }}
          onClear={() => setTimeTypeFilter('')}
        >
          <Select.Option value="">全部时间类型</Select.Option>
          {Object.entries(TIME_TYPE_LABELS).map(([key, label]) => (
            <Select.Option key={key} value={key}>{label}</Select.Option>
          ))}
        </Select>
        {personNameFilter && (
          <Tag
            closable
            color="blue"
            onClose={clearPersonFilter}
          >
            筛选：{personNameFilter}
          </Tag>
        )}
      </div>

      <Table
        dataSource={store.list}
        columns={columns}
        rowKey="id"
        loading={store.listLoading}
        pagination={false}
        size="middle"
        locale={{ emptyText: '暂无事件数据' }}
      />

      {store.total > store.pageSize && (
        <div className="mt-4 flex justify-end">
          <Pagination
            current={currentPage}
            pageSize={store.pageSize}
            total={store.total}
            showTotal={total => `共 ${total} 条`}
            onChange={p => setCurrentPage(p)}
            showSizeChanger={false}
          />
        </div>
      )}

      <EventFormDialog
        open={dialogOpen}
        eventId={editingEventId}
        onClose={() => setDialogOpen(false)}
        onSaved={fetchData}
      />
    </div>
  )
}
